### ISSUE TITLE
App Crash Report

### ISSUE THREAD

**Issue by cbutlerp** [agrc/api-client#129] opened 2022-04-12 19:02 UTC
### What happened?

App started successfully after dragging in cvs file. It stopped working  and never completed even thought it had already processed many of the rows. I reported this same problem a week or so ago. It has never been fixed, even thought the help desk sent me an email that said it had been resolved. I have a lot of addresses that I need to submit. When will this bug be fixed?
Cindy

### Steps To Reproduce

try dragging a cvs file of addresses yourself and using the UT standard gis reference

### App Version

1.5.7

### Electron Version

17.0.0

### Operating System

macOS Monterey

#### Error message

`Error invoking remote method 'geocode': TypeError: Cannot read properties of undefined (reading 'statusCode')`

#### Stack trace

```st
Error: Error invoking remote method 'geocode': TypeError: Cannot read properties of undefined (reading 'statusCode')
```

**Comment by steveoh** [comment] 2022-04-12 19:20
They resolved the ticket because we are tracking the issue in this repository. We haven't had time to work on this bug yet. But please follow along with the original issue which we are tracking at https://github.com/agrc/api-client/issues/122. Then you will know when we can get to it and ultimately resolve the issue.

If our timeline is not acceptable to you, we do have other ways to geocode. If you have arcgis software we have a toolbox available or if you know how to write code, the api is ready to handle your geocoding job.

Since this is a duplicate of #122 I am going to close this issue. Thank you for the reminder that people are having problems.

**Closed by steveoh** 2022-04-12 19:20 UTC

**Comment by cbutlerp** [comment] 2022-04-13 00:47
Thank you for your quick response, Love the App! you guys are awesome!
C
